name: Publish
on:
  push:
    branches:
      - add-publish-action

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: setup node env
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'

      - name: setup Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: install dependencies
        run: yarn install --immutable

      - name: build package
        run: yarn build:dist

      - name: publish package
        run: npm publish --access public
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
